# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only

# ---
# tasks file for roles/org

# # ########################################### Get the Organization Status #############################################
- name: Get Organisation State
  set_fact:
    org_state: "{{ state }}"

# # ############################################ Create/Update Org ##############################################################
- name: create org
  vcd_org:
    user: XXXXXXXXXX
    password: XXXXXXXXXX
    host: XXXXXXXXXX
    org: XXXXXXXXXX
    org_name: "{{ org_name }}"
    full_name: "{{ org_full_name }}"
    is_enabled : "{{ is_enabled }}"
    state: {{ org_state }}
  register: output
  when: state == "present" or state == "update"

- name: delete org output
  debug:
    msg: '{{ output }}'

# # ############################################ Delete Org ##############################################################
- name: delete org
  vcd_org:
    user: XXXXXXXXXX
    password: XXXXXXXXXX
    host: XXXXXXXXXX
    org: XXXXXXXXXX
    org_name: "{{ org_name }}"
    force: "{{ force }}"
    recursive: "{{ recursive }}"
    state: {{ org_state }}
  register: output
  when: state == "absent"

- name: delete org output
  debug:
    msg: '{{ output }}'

